name: Build Angular Editor

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/Sharp-O-Matic.Editor/**'
  pull_request:
    paths:
      - 'src/Sharp-O-Matic.Editor/**'

jobs:
  build-angular:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'src/Sharp-O-Matic.Editor'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'src/Sharp-O-Matic.Editor/package-lock.json'          

      - name: Install dependencies
        run: npm ci              

      - name: Build Angular app
        run: npm run build
